
  server:
    port: 0

  client:
    url: http://stats-server:9090
  spring:
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://ewm-db:5432/ewm-main
      username: root
      password: root

    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true