
        server:
          port: 9090
        spring:
          application:
            name: stats-server
          jpa:
            show-sql: true
            hibernate:
              ddl-auto: none
            properties:
              hibernate:
                format_sql: true
            defer-datasource-initialization: true
          sql:
            init:
              mode: always
          output:
            ansi:
              enabled: ALWAYS
          datasource:
            datasource:
              driverClassName: org.postgresql.Driver
              url: jdbc:postgresql://stats-db:5432/ewm-stats
              username: root
              password: root
