spring:
  application:
    name: user-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
server:
  port: ${SERVER_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instanceId: "${spring.application.name}:${server.port}"
    leaseRenewalIntervalInSeconds: 10