server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
              - Path=/admin/users/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
               - Path=/users/*/events/*/comments/**, /events/*/comments/**
        - id: request-service
          uri: lb://request-service
          predicates:
              - Path=/users/*/requests/**, /requests/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
              - Path=/hit/**, /stats/**
        - id: event-service
          uri: lb://event-service
          predicates:
              - Path=/admin/events/**, /users/*/events/**, /users/*/events/*/requests/**, /events/**, /categories/**,
                /admin/categories/**, /admin/compilations/**, /compilations/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true